### ISSUE TITLE
inquirer-recursive doesn't work with inquirer@0.12.0 installed by plop

### ISSUE THREAD

**Issue by R0bson** [amwmedia/plop#56]
Hey, I just tried plop with inquirer-recursive and each time plop comes to prompt with recursive question it fails with error given below.

I resolved the issue by updating inquirer@0.12.0 to inquirer@2.0.0. At the moment inquirer-recursive works properly and nothing have broke so it's not an issue for me, but some other people may be misguided by https://github.com/amwmedia/plop/blob/master/inquirer-prompts.md.
I will suggest to:
 - place proper information in documentation that inquirer-recursive may need to upgrade inquirer to newer version
 - or consider upgrading plop's inquirer dependency 
 - or maybe there is an issue with node 6.5.0 compatibility (this will be an issue for inquirer of course)

plop: 1.7.3
OS: Windows 10
Node: 6.5.0

Receivied error:
```
[ERROR] inquirer.prompt(...).then is not a function TypeError: inquirer.prompt(...).then is not a function
at Prompt.askForLoop (@project_folder@\node_modules\inquirer-recursive\index.js:27:8)
at Prompt._run (@project_folder@\node_modules\inquirer-recursive\index.js:46:10)
at Prompt.run (@project_folder@\node_modules\inquirer\lib\prompts\base.js:55:8)
at @Roaming_folder@\nvm\v6.5.0\node_modules\plop\node_modules\inquirer\lib\ui\prompt.js:79:45
at tryCatcher (@Roaming_folder@\nvm\v6.5.0\node_modules\plop\node_modules\rx\dist\rx.js:63:31)
at Defer.subscribeCore (@Roaming_folder@\nvm\v6.5.0\node_modules\plop\node_modules\rx\dist\rx.js:2536:37)
at Defer.tryCatcher (@Roaming_folder@\nvm\v6.5.0\node_modules\plop\node_modules\rx\dist\rx.js:63:31)
at setDisposable (@Roaming_folder@\nvm\v6.5.0\node_modules\plop\node_modules\rx\dist\rx.js:2082:46)
at Defer.Rx.ObservableBase.ObservableBase._subscribe (@Roaming_folder@\nvm\v6.5.0\node_modules\plop\node_modules\rx\dist\rx.js:2097:9)
at Defer.Rx.Observable.observableProto.subscribe.observableProto.forEach (@Roaming_folder@\nvm\v6.5.0\node_modules\plop\node_modules\rx\dist\rx.js:2034:19)
```

**Comment by amwmedia** [comment]
That's really strange because plop 1.7.3 depends on inquirer "^1.2.0". So it uses a version of inquirer that runs on promises. I'll do some tests tomorrow on plop's compatibility with this plugin. Any ideas @nathanloisel?

**Comment by R0bson** [comment]
Well I see that I made a mistake... 
I haven't checked real plop dependencies^^


After deeper search I found that in my repo eslint@3.12.2 has dependency on inquirer@0.12.0 while plop actually has a dependency on inquirer@1.2.0. 
I don't know why but in some strange way npm resolved this conflict with global inquirer package with version 0.12.0 and put inquirer@1.2.0 in node_plop/node_modules, but on require in node_plop resolved with global package...

So now it comes that this is issue with proper package resolving :)

**Comment by amwmedia** [comment]
that makes a lot more sense.

**Comment by Akiyamka** [comment]
Can anyone provide example of use inquirer-recursive in plop?

**Comment by amwmedia** [comment]
There is example code on the [github readme page](https://github.com/nathanloisel/inquirer-recursive)
